### PR TITLE
Port to Python 3

### LINKED ISSUE #2: Port to Python 3
Port Sugargame to Python 3 and the Sugar Toolkit for GTK+ 3.

Requires some of https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/382 to be completed.

### PR DESCRIPTION
**Pull request by rhl-bthr**
Fixes #2

### CODE REVIEW

**Comment by rhl-bthr** [comment]
Instead of making a separate package for `sugargame` (re my earlier suggestion), maybe we can include `sugargame` in `sugar-toolkit-gtk3`.
```python
from sugargame import event
```
would become
```python
from sugar3.sugargame import event
```

advantage would again be reduced code maintainence

**Comment by quozl** [comment]
Thanks.  Reviewed to eaf97fb.  Waiting on toolkit release.

> maybe we can include sugargame in sugar-toolkit-gtk3
> advantage would again be reduced code maintainence

Yes, it would be an advantage.  However a disadvantage would be adding pygame as a dependency to the toolkit, which will force Pygame and SDL to be installed even if a system does not have activities that need them.

Let's have some numbers; how many activities use sugargame, how many do not, and how large is Pygame on a typical amd64 architecture system?

On my development system, there are 15 activities that use sugargame out of 108 activities, and Pygame is about 1.6 MB, with SDL about 1 MB.

**Comment by Aniket21mathur** [comment]
@quozl We have the toolkit released and might proceed further. Thanks!

**Comment by quozl** [comment]
Is incomplete, because toolkit is incomplete;

```
Traceback (most recent call last):
  File "/usr/local/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/local/lib/python3.7/dist-packages/sugar3/activity/activityinstance.py", line 178, in main
    module = __import__(module_name)
  File "/home/guest/sugargame/test/TestActivity.py", line 9, in <module>
    from sugar3.activity.activity import Activity
  File "/usr/local/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 184, in <module>
    from telepathy.server import DBusProperties
ModuleNotFoundError: No module named 'telepathy'
```

As there is no published Python 3 port of the static bindings for Telepathy, we must use TelepathyGLib instead.

**Comment by rhl-bthr** [comment]
@quozl @aniket21mathur, please review

**Comment by Aniket21mathur** [comment]
Thanks. Reviewed!

**Pull request merged**
